# Generated by Django 5.1.4 on 2024-12-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='home_project',
        ),
    ]
