# Generated by Django 5.1.4 on 2024-12-19 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_installnation_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='installnation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.project'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.project'),
        ),
    ]
